#!/bin/bash
#remove (#) to run specific set of tests

#runs test by api and separates results

#./karate -e stg ccte-api/bioactivity
./karate -e stg ccte-api/chemical
#./karate -e stg ccte-api/hazard

#runs all tests together

#./karate -e stg ccte-api
