#!/bin/bash
./karate -e prod ccte-api/security/security-chemical.feature
./karate -e prod ccte-api/security/security-bioactivity.feature
./karate -e prod ccte-api/security/security-hazard.feature
./karate -e stg ccte-api/security/security-exposure.feature
