#!/bin/bash
//this creates individual html displays each API
./karate ccte-api/bioactivity
./karate ccte-api/chemical
./karate ccte-api/hazard

//this will create an html file that displays them all at once
#./karate ccte-api
