#!/bin/bash
java -jar karate-1.4.1.jar -t @regression -e stg ccte-api/bioactivity
java -jar karate-1.4.1.jar -t @regression -e stg ccte-api/chemical
java -jar karate-1.4.1.jar -t @regression -e stg ccte-api/hazard
